\documentclass[a4paper]{article}
\usepackage{pdflscape}
\usepackage{graphicx}
\usepackage[margin = 1 cm]{geometry}

\begin{document}

Illumina characterizes probes into 6 categories: TSS1500, TSS200, 5' UTR, 1st exon, gene body, and 3' UTR.
Promoter regions were divided into two, mutually exclusive bins of 200 bp and 1500 bp blocks upstream of the
transcription start site (designated TSS200 and TSS1500, respectively).

\begin{landscape}
<<signif_genes, dev = "pdf", results = 'asis', echo = FALSE, sanitize = TRUE, fig.show = 'hold'>>=
library(xtable)


for (j in 1:length(candidate.genes)) {
  for (i in 1:length(bhv.vars)){
    names(regr.site.pv[[i]]) <- rownames(hm450)
    pval.sort <- sort(regr.site.pv[[i]])

    pval.annot <- hm450[names(pval.sort), c(17, 18, 20, 22)]
    assoc.genes <- data.frame(names(pval.sort), pval.sort, pval.annot)

    food.genes <- NULL
    for (gene in candidate.genes[[j]]) {
      pattern <- paste0(";", gene, ";|^", gene, ";|;", gene, "$")
      food.genes <- rbind(food.genes, assoc.genes[grep(pattern,assoc.genes$UCSC_RefGene_Name),])
    }
    food.genes <- arrange(food.genes, pval.sort)
    food.genes.sig <- unique(food.genes[1:40,])[1:20,]

    uniqueGenes <- function(vec) {
      tmp <- lapply(strsplit(vec,";"),unique)
      unlist(lapply(tmp, paste0, collapse=";")) # cat doesn't work
    }

    food.genes.sig$UCSC_RefGene_Name <- uniqueGenes(food.genes.sig$UCSC_RefGene_Name)
    food.genes.sig$UCSC_RefGene_Group <- uniqueGenes(food.genes.sig$UCSC_RefGene_Group)

    behav.caption <- paste0("geneSet-", names(candidate.genes)[j],", ", gsub("_", "-", bhv.vars[i]))

  	print(xtable(food.genes.sig, digits = -3, caption = behav.caption),
          sanitize.text.function=function(str)gsub("_"," ",str,fixed=TRUE))
  }
}
cat('\\clearpage\n')
@
\end{landscape}
\end{document}